//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GinieLive.Notify {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MsgSoap", Namespace="http://ginie.live/")]
    public partial class Msg : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AskHelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Msg() {
            this.Url = global::GinieLive.Properties.Settings.Default.GinieLive_Notify_Msg;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AskHelloWorldCompletedEventHandler AskHelloWorldCompleted;
        
        /// <remarks/>
        public event EmailCompletedEventHandler EmailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ginie.live/AskHelloWorld", RequestNamespace="http://ginie.live/", ResponseNamespace="http://ginie.live/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AskHelloWorld() {
            object[] results = this.Invoke("AskHelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AskHelloWorldAsync() {
            this.AskHelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void AskHelloWorldAsync(object userState) {
            if ((this.AskHelloWorldOperationCompleted == null)) {
                this.AskHelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAskHelloWorldOperationCompleted);
            }
            this.InvokeAsync("AskHelloWorld", new object[0], this.AskHelloWorldOperationCompleted, userState);
        }
        
        private void OnAskHelloWorldOperationCompleted(object arg) {
            if ((this.AskHelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AskHelloWorldCompleted(this, new AskHelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ginie.live/Email", RequestNamespace="http://ginie.live/", ResponseNamespace="http://ginie.live/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Email(string EmailId, string Subject, string Message, string Sender, string Appkey) {
            object[] results = this.Invoke("Email", new object[] {
                        EmailId,
                        Subject,
                        Message,
                        Sender,
                        Appkey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailAsync(string EmailId, string Subject, string Message, string Sender, string Appkey) {
            this.EmailAsync(EmailId, Subject, Message, Sender, Appkey, null);
        }
        
        /// <remarks/>
        public void EmailAsync(string EmailId, string Subject, string Message, string Sender, string Appkey, object userState) {
            if ((this.EmailOperationCompleted == null)) {
                this.EmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailOperationCompleted);
            }
            this.InvokeAsync("Email", new object[] {
                        EmailId,
                        Subject,
                        Message,
                        Sender,
                        Appkey}, this.EmailOperationCompleted, userState);
        }
        
        private void OnEmailOperationCompleted(object arg) {
            if ((this.EmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailCompleted(this, new EmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AskHelloWorldCompletedEventHandler(object sender, AskHelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AskHelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AskHelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void EmailCompletedEventHandler(object sender, EmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591